### PR TITLE
Add example DAG for databricks delta support

### PR DESCRIPTION
**Pull request by dimberman**
# Description
## What is the current behavior?
The Astro SDK currently does not have an example for loading, transforming, and processing data using Databricks' delta tables.

## What is the new behavior?
This PR adds an example to the Astro SDK for loading, transforming, and processing data using Databricks' delta tables. The example includes the following steps:
- Loading data from a CSV file in an s3 bucket into a delta table using the `load_file` function.
- Transforming the data using Databricks delta SQL SDK and astro's `transforn` function
- Moving resulting data into a pandas dataframe using the `aql.dataframe` function.

## Does this introduce a breaking change?
No, this is a new feature and does not affect existing functionality.

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by kaxil** [comment]
@dimberman Can you get this to the finish line please?

**Review by tatiana — APPROVED** [review]
Happy for this PR to be merged once the checks pass

**Comment by dimberman** [comment]
@tatiana @kaxil so this PR runs fine in my local set up but it fails in CI due to https://github.com/astronomer/astro-sdk/issues/1744. Should we wait until we've solved #1744 before merging this PR or merge now and then solve?

**Comment by tatiana** [comment]
@dimberman, it would be great if we could address CI issue #1744. before merging this..! How is that going?

**Pull request closed without merging**
