### PR TITLE
Update the open lineage documentation

### PR DESCRIPTION
**Pull request by sunank200**
# Description
## What is the current behavior?

Update the open lineage doc with correct configurations and example DAG

closes: #1880

## What is the new behavior?

- Update the open lineage documentation with configurations
- Update the example DAG

## Does this introduce a breaking change?
No

### Checklist
- [x] Created tests which fail without the change (if possible)
- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by sunank200** [comment]
Screenshot 2023-03-31 at 6 32 09 PM
Screenshot 2023-03-31 at 6 32 18 PM

**Comment by sunank200** [comment]
Screenshot 2023-04-03 at 3 08 14 PM
Changed the images as well

**Review by tatiana — APPROVED** [review]
Thanks a lot for addressing the original concerns/issues I raised last week, @sunank200 !

Two additional minor requests:
* Please, add a link to Marquez installation notes, and say that this example works with it.
* There is a misspelling: "By default, we emit the temporary tables event in openlienage."  (openlienage -> openlineage), please, fix any issues with spelling.

**Comment by sunank200** [comment]
Screenshot 2023-04-04 at 8 20 09 PM


> Thanks a lot for addressing the original concerns/issues I raised last week, @sunank200 !
> 
> Two additional minor requests:
> 
> * Please, add a link to Marquez installation notes, and say that this example works with it.
> * There is a misspelling: "By default, we emit the temporary tables event in openlienage."  (openlienage -> openlineage), please, fix any issues with spelling.

@tatiana I have updated the link for Marquez installation and addressed the above comment.

**Pull request merged**
