### PR TITLE
Sharepoint integration

### PR DESCRIPTION
**Pull request by Lee-W**
# Description
## What is the current behavior?

close: #1553

## What is the new behavior?

-
-
-

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by dimberman** [comment]
Hi @Lee-W, can you please provide more information on this PR's description? The issue request is a bit convoluted so it would be great to see a description that tells us

a) what sharepoint is
b) how we're integrating it
c) if there are any caveats or limitations to this integration

Thank you!

**Comment by phanikumv** [comment]
Blocked on sharepoint access

**Comment by phanikumv** [comment]
@Lee-W whats the latest on the sharepoint access? Have you been able to talk to IT and get it resolved?

**Comment by phanikumv** [comment]
You've got access to Sharepoint now @Lee-W , lets move forward on this based on priority

**Comment by sunank200** [comment]
@Lee-W any timeline with respect to this issue?

**Comment by Lee-W** [comment]
I'm still focused on auto switch deferrable. Will be able to work on it after that

**Pull request closed without merging**
