### PR TITLE
Add `.coveragerc` to the project

### PR DESCRIPTION
**Pull request by pankajastro**
# Description
## What is the current behavior?
Add frequently code coverage excluded line in `.coverragerc`

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Review by pankajkoti — COMMENTED** [review]
I don't think Codecov supports exclude_lines that well. It does not ignore the whole if block or except block.

Screenshot 2022-11-14 at 12 55 37 PM

**Comment by feluelle** [comment]
@pankajastro I don't think setting this in the rc file works. I already tried that before.

**Comment by tatiana** [comment]
Hey @pankajastro , do we still want to merge this? :)

**Comment by pankajastro** [comment]
> Hey @pankajastro , do we still want to merge this? :)

closing this PR for now. I'll reopen again once start working on this.

**Pull request closed without merging**
