### PR TITLE
Docs: add "Operators" to "Reference" 

### LINKED ISSUE #694: Docs: add "Operators" to "Reference" and to have "Concepts" include some more high level documentation
Looks a lot cleaner! I don't feel strongly either way, but in the future it might make sense to add "Operators" to "Reference" and to have "Concepts" include some more high level documentation. Knowing what each operator does _seems_ more referency to me. 

But because "Concepts" is only one doc for now, I think this structure works for the content we have.

_Originally posted by @jwitz in https://github.com/astronomer/astro-sdk/pull/692#pullrequestreview-1077794972_

### PR DESCRIPTION
**Pull request by rajaths010494**
Move  "Operators"  from "Guides" section to "Reference" section.
closes #694

### CODE REVIEW

**Review by pankajastro — COMMENTED** [review]
Hey @rajaths010494 are you planning to add the concept docs for operators also here?

**Comment by rajaths010494** [comment]
> Hey @rajaths010494 are you planning to add the concept docs for operators also here?

Is there any new concepts which would need to me to add in docs.

**Comment by pankajastro** [comment]
> future it might make sense to add "Operators" to "Reference" and to have "Concepts" include some more high level documentation

ticket description says 
> future it might make sense to add "Operators" to "Reference" and to have "Concepts" include some more high level documentation

**Comment by pankajastro** [comment]
Also, the PR description does not look correct.

**Comment by sunank200** [comment]
> Also, the PR description does not look correct.

+1

**Comment by sunank200** [comment]
Agree with @pankajastro on the comment he made on the issue. I am not very clear with issue description and PR description as well.

cc: @rajaths010494

**Review by pankajkoti — COMMENTED** [review]
The description says Concepts to have some more high level documentation, do we plan to add anything in Concepts? If not can we update the description?  Also, then since it only partly addresses the ticket, I think we should change the hash tag from `closes` to `related` in the description.

**Comment by pankajastro** [comment]
Response from user
> @pankajastro We can close this issue because my thoughts have evolved a bit since I wrote that message. Overall, I think the SDK guides should focus on "How to" guides for common actions/ pipeline structures, rather than for the operators themselves. So example, instead of a guide called drop table operator, we have a guide called "Drop a table"

**Pull request closed without merging**
