### PR TITLE
Revert "Limit Pydantic < 2.0.0 until Airflow resolves incompatibilities"

### PR DESCRIPTION
**Pull request by pankajastro**
Reverts astronomer/astro-sdk#1981

### CODE REVIEW

**Review by tatiana — APPROVED** [review]
@pankajastro it looks great, thanks!
What do you think of removing the micro version and pinning only on the minor one? This way we can test the latest 2.6 releases

**Comment by pankajastro** [comment]
> What do you think of removing the micro version and pinning only on the minor one? This way we can test the latest 2.6 releases

sorry @tatiana , I'm a bit confused are you talking about pinning a minor version of Airflow not micro for example pin 2.6 and not 2.6.3?

**Comment by pankajastro** [comment]
> > What do you think of removing the micro version and pinning only on the minor one? This way we can test the latest 2.6 releases
> 
> sorry @tatiana , I'm a bit confused are you talking about pinning a minor version of Airflow not micro for example pin 2.6 and not 2.6.3?

I run `pip install apache-airflow==2.6` in a clean Python virtual env and it installed 2.6.0 and not the latest (2.6.3).
I selected the last patch because I feel it most stable for a given minor version

**Comment by pankajastro** [comment]
> > > What do you think of removing the micro version and pinning only on the minor one? This way we can test the latest 2.6 releases
> > 
> > 
> > sorry @tatiana , I'm a bit confused are you talking about pinning a minor version of Airflow not micro for example pin 2.6 and not 2.6.3?
> 
> I run `pip install apache-airflow==2.6` in a clean Python virtual env and it installed 2.6.0 and not the latest (2.6.3). I selected the last patch because I feel it most stable for a given minor version

I tried to use `2.6.*` but in this case, it uses cache if available so maybe it would not install latest until we pass no-cache param

**Comment by pankajastro** [comment]
I address the CI config changes in a separate PR since the original purpose of this PR was to revert https://github.com/astronomer/astro-sdk/pull/1981 and the ci config came into the picture since tests were failing. thank you @tatiana for the clarification.

**Pull request merged**
