### PR TITLE
Remove condition import for SQLAlcRow

### PR DESCRIPTION
**Pull request by pankajastro**
since airflow is pin to >2.7.0 remove conditional import 
https://github.com/astronomer/astro-sdk/blob/main/python-sdk/pyproject.toml#L20

### CODE REVIEW

**Comment by Lee-W** [comment]
Looks like the CI is failing. Just rerun it. Let's see how it works

**Review by pankajkoti — APPROVED** [review]
LGTM. Some tests seems to be failing. Should we fix them in this PR or a subsequent PR is better? Leaving the call to you to decide @pankajastro

**Comment by Lee-W** [comment]
> Looks like the CI is failing. Just rerun it. Let's see how it works

It still fails. I think we might need to check it 🤔

**Comment by pankajastro** [comment]
> It still fails. I think we might need to check it 🤔

Yes, it is broken since 2.9 I'm fixing in https://github.com/astronomer/astro-sdk/pull/2149

**Comment by pankajastro** [comment]
> GTM. Some tests seems to be failing. Should we fix them in this PR or a subsequent PR is better? Leaving the call to you to decide @pankajastro

yeah, the failure is unrelated to this change, I'll merge this one to fix the import error in example DAG and will fix CI in https://github.com/astronomer/astro-sdk/pull/2149

**Pull request merged**
