### PR TITLE
Removing 'Kaxil' from Code Owner

### PR DESCRIPTION
**Pull request by kaxil**
I won't be able to review alot of PRs given the time constraints

### CODE REVIEW

**Review by tatiana — APPROVED** [review]

**Comment by tatiana** [comment]
:'(

**Review by pankajkoti — COMMENTED** [review]
Why do we need this change?

**Comment by tatiana** [comment]
No one wants to merge this PR, @kaxil. Do you feel it's necessary to stop receiving Python SDK PRs notifications? We could still just close it and pretend it never happened :joy:

**Review by phanikumv — APPROVED** [review]

**Comment by kaxil** [comment]
:) I plan to be absolutely be back in a few months with a bang. This change (_I hope_) will be very temporary

**Pull request merged**
