### PR TITLE
[DO NOT MERGE] Test RC provider packages

### PR DESCRIPTION
**Pull request by rajaths010494**
# Description
## What is the new behavior?

-
-
-

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by pankajkoti** [comment]
I re-ran one of the failing tests and perhaps we can ignore the test-3.8(airflow='2.2.5') failing test? 
cc: @phanikumv @rajaths010494 @pankajastro @utkarsharma2 ?

**Review by pankajkoti — COMMENTED** [review]
I re-ran one of the failing tests and perhaps we can ignore the test-3.8(airflow='2.2.5') failing test?
cc: @phanikumv @rajaths010494 @pankajastro @utkarsharma2 ?

**Comment by pankajastro** [comment]
> I re-ran one of the failing tests and perhaps we can ignore the test-3.8(airflow='2.2.5') failing test? cc: @phanikumv @rajaths010494 @pankajastro @utkarsharma2 ?

hmm, actually we installed airflow in ci with constraints file https://github.com/astronomer/astro-sdk/blob/main/python-sdk/noxfile.py#L39 maybe be because of that it throwing azure provider version mismatch error

**Comment by pankajastro** [comment]
> I re-ran one of the failing tests and perhaps we can ignore the test-3.8(airflow='2.2.5') failing test?
> cc: @phanikumv @rajaths010494 @pankajastro @utkarsharma2 ?

yes, if we are testing core rc then 2.2.5 error we can ignore. just I have rerun it on 2.5.1rc2 as well one test has fail does not look related to core airflow changes https://github.com/astronomer/astro-sdk/actions/runs/3962557251/jobs/6789377133

**Pull request closed without merging**
