### PR TITLE
Improve logging for load_file

### PR DESCRIPTION
**Pull request by feluelle**
# Description

## What is the current behavior?

Currently, we don't have any logging for native nor pandas _load_file_. This makes it harder for users to follow the operations.

related: #1263

## What is the new behavior?

We now have log statements for native, pandas as well as fallback indication.

## Does this introduce a breaking change?

No.

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Review by tatiana — APPROVED** [review]
@feluelle would it make sense to have a test covering this change? Approving it regardless, since the change already helps users.

**Review by kaxil — APPROVED** [review]

**Review by kaxil — COMMENTED** [review]
One test failed for Airflow 2.4 and 2.2.5:

```
google.api_core.exceptions.BadRequest: 400 Provided Schema does not match Table astronomer-dag-authoring:first_table_schema._tmp_gcuqy9jbp3wxal8q0uqwb8jrk2a2zr6zage4t0g. Field id has changed mode from REQUIRED to NULLABLE
```

**Review by pankajkoti — APPROVED** [review]

**Comment by pankajkoti** [comment]
> One test failed for Airflow 2.4 and 2.2.5:
> 
> ```
> google.api_core.exceptions.BadRequest: 400 Provided Schema does not match Table astronomer-dag-authoring:first_table_schema._tmp_gcuqy9jbp3wxal8q0uqwb8jrk2a2zr6zage4t0g. Field id has changed mode from REQUIRED to NULLABLE
> ```

I checked this and seems that it is because we explicitly specify ID is primary key in the target table and hence it becomes REQUIRED. Whereas in the source table, we directly load data from file without specifying the schema. 

Screenshot 2022-11-29 at 1 38 23 PM

As a result, the schema for the target table has ID as REQUIRED:
Screenshot 2022-11-29 at 1 40 22 PM


whereas, the source table has ID as NULLABLE:
Screenshot 2022-11-29 at 1 40 59 PM


So perhaps should we add the columns key in the source Table to specify that it is a primary key?

**Comment by pankajkoti** [comment]
I tried doing that(specifying columns), but got the following error, so reverting my commit.

Screenshot 2022-11-29 at 2 12 42 PM

**Pull request merged**
