### PR TITLE
[DO NOT MERGE] Delete temp tables snowflake

### PR DESCRIPTION
**Pull request by rajaths010494**
# Description
## What is the new behavior?

-
-
-

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by sunank200** [comment]
How is this deletion coming along @rajaths010494 ?

**Comment by rajaths010494** [comment]
> How is this deletion coming along @rajaths010494 ?

Pretty much done. I will close once the last few tables also get deleted.

**Comment by sunank200** [comment]
> > How is this deletion coming along @rajaths010494 ?
> 
> Pretty much done. I will close once the last few tables also get deleted.

  How is this deletion coming along @rajaths010494 ?

**Comment by rajaths010494** [comment]
We no longer this PR since cleanup snowflake is already implemented.

**Pull request closed without merging**
