### PR TITLE
Add CODEOWNERS

### PR DESCRIPTION
**Pull request by pankajkoti**
Add CODEOWNERS for the repository.

Reference: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

### CODE REVIEW

**Comment by pankajastro** [comment]
Please add Felix also.

**Comment by pankajkoti** [comment]
> Please add Felix also.

I was not sure what Github ID he is planning to use. @feluelle can you confirm your Github ID you would like to use?

**Comment by pankajkoti** [comment]
Looks like @feluelle does not have write access to the repository yet & hence it is complaining that the CODEOWNERS file is not valid. 
Screenshot 2022-08-10 at 5 00 01 PM

@kaxil can you please confirm the CODEOWNERS for the repository are correct in the PR and check that they have write permissions?

**Comment by kaxil** [comment]
>Looks like @feluelle does not have write access to the repository yet

Fixed it, I created a Github group: https://github.com/orgs/astronomer/teams/dag-authoring-team/members - @astronomer/dag-authoring-team

**Review by kaxil — APPROVED** [review]

**Comment by kaxil** [comment]
Thanks @pankajkoti 🎉

**Pull request merged**
