### PR TITLE
Move databricks module into the databases directory

### PR DESCRIPTION
**Pull request by dimberman**
# Description
## What is the current behavior?
Currently the "databricks" module lives at the top level of the python SDK, this can be somewhat confusing as it might lead users to think there is non-database functionality in the databricks module. By moving the databricks module into the database module, we insulate the class and ensure that it is treated like any other database going forward.

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Review by tatiana — APPROVED** [review]
Great to see it together with the other databases! I'm happy for it to be merged once the checks are passing.

I wonder if, in a separate ticket, we could try to extend existing fixtures for other DBs and try to unify a bit of tests for `load_file` and `export_file`

**Review by pankajastro — APPROVED** [review]

**Comment by kaxil** [comment]
image

2 of the 3 suggestions from deep source should be fixed -- but since it wasn't added in this PR, please create a separate PR to fix those

**Comment by phanikumv** [comment]
Sure @kaxil - we will create a PR for that

cc @pankajastro

**Comment by pankajastro** [comment]
> Sure @kaxil - we will create a PR for that
> 
> cc @pankajastro

@phanikumv @kaxil I tried to make changes in these files to re-produce it but I'm unable to re-reproduce https://github.com/astronomer/astro-sdk/pull/1565

**Pull request merged**
